# Generated by Django 5.2.1 on 2025-05-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingredients', models.JSONField()),
                ('instructions', models.JSONField()),
                ('prepTimeMinutes', models.IntegerField()),
                ('cookTimeMinutes', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('difficulty', models.CharField()),
                ('cuisine', models.CharField()),
                ('caloriesPerServing', models.FloatField()),
                ('tags', models.JSONField()),
                ('image', models.URLField()),
                ('rating', models.FloatField()),
                ('reviewCount', models.IntegerField()),
                ('mealType', models.JSONField()),
            ],
        ),
    ]
